<div id="{{$componentId}}">
    <x-media::gallery
            :mediaFiles="$mediaFiles"
            :id="$idGallery" :zones="$zones"
            :margin="$margin"
            :responsiveClass="$responsiveClass"
            :autoplay="$autoplay"
            :autoplayHoverPause="$autoplayHoverPause"
            :loopGallery="$loopGallery"
            :dots="$dots" :nav="$nav"
            :showNavs="$showNavs"
            :responsive="$responsive"
            :dataFancybox="$dataFancybox"
            :layout="$layout"
            :columnMasonry="$columnMasonry"
            :maxImages="$maxImages"
            :onlyVideos="$onlyVideos"
            :onlyImages="$onlyImages"
            :autoplayVideo="$autoplayVideo"
            :mutedVideo="$mutedVideo"
            :loopVideo="$loopVideo"
            :stagePadding="$stagePadding"
            :autoplayTimeout="$autoplayTimeout"
            :aspectRatio="$aspectRatio"
            :objectFit="$objectFit"
            :showDescription="$showDescription"
            :marginItems="$marginItems"
            :heightItems="$heightItems"
    />
</div>
